# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: salman-terraform
  vmImage: agent-0777

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV3@3
  displayName: 'Terraform init'
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceAWS: 'aws-terraform'
    backendAWSBucketName: 'terraform-aws-1075'
    backendAWSKey: 'terraform.tfstate'

- task: TerraformTaskV3@3
  displayName: 'Terraform plan'
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'aws-terraform'

- task: TerraformTaskV3@3
  displayName: 'Terraform apply'
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-terraform'

- task: TerraformTaskV3@3
  displayName: 'Terraform destroy'
  inputs:
    provider: 'aws'
    command: 'destroy'
    environmentServiceNameAWS: 'aws-terraform'
