trigger:
- none
pool:
 name: salman-terraform
 vmImage: agent-0777
stages:
  - stage: Purple02758&!*
    jobs:
    - job: Surple02758&!*
      steps:
      - task: TerraformTaskV3@3
        displayName: Terraform INIT
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
          backendServiceAWS: 'aws-terraform'
          backendAWSBucketName: 'terraform-aws-1075'
          backendAWSKey: 'terraform.tfstate'

      - task: TerraformTaskV3@3
        displayName: Terraform PLAN
        inputs:
          provider: 'aws'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
          environmentServiceNameAWS: 'aws-terraform'
      - task: TerraformTaskV3@3
        displayName: Terraform Apply
        inputs:
          provider: 'aws'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
          environmentServiceNameAWS: 'aws-terraform'

  - stage: Xurple02758&!*
    jobs:
    - job: Jurple02758&!*
      steps:
      - task: TerraformTaskV3@3
        displayName: Terraform INIT
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/ALB'
          backendServiceAWS: 'aws-terraform'
          backendAWSBucketName: 'terraform-aws-1075'
          backendAWSKey: 'terraform.tfstate'

      - task: TerraformTaskV3@3
        displayName: Terraform Apply
        inputs:
          provider: 'aws'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/ALB'
          environmentServiceNameAWS: 'aws-terraform'
                  
     
