trigger:
- none
pool:
 name: salman-terraform
 vmImage: agent-0777
stages:
  - stage: creating instance and vpc
    jobs:
      - job: creating instance and vpc
        steps:
        - task: TerraformTaskV3@3
          displayName: Terraform INIT
          inputs:
            provider: 'aws'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
            backendServiceAWS: 'aws-terraform'
            backendAWSBucketName: 'terraform-aws-1075'
            backendAWSKey: 'terraform.tfstate'

        - task: TerraformTaskV3@3
          displayName: Terraform PLAN
          inputs:
            provider: 'aws'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
            environmentServiceNameAWS: 'aws-terraform'
        - task: TerraformTaskV3@3
          displayName: Terraform Apply
          inputs:
            provider: 'aws'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/EC2_VPC'
            environmentServiceNameAWS: 'aws-terraform'

  - stage: creating aLB
    jobs:
      - job: creating aLB
        steps:
        - task: TerraformTaskV3@3
          displayName: Terraform INIT
          inputs:
            provider: 'aws'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/ALB'
            backendServiceAWS: 'aws-terraform'
            backendAWSBucketName: 'terraform-aws-1075'
            backendAWSKey: 'terraform.tfstate'

        - task: TerraformTaskV3@3
          displayName: Terraform Apply
          inputs:
            provider: 'aws'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/ALB'
            environmentServiceNameAWS: 'aws-terraform'
                  
     
