trigger:
- none
pool:
 name: salman-terraform
 vmImage: agent-0777
stages:
  - stage: Createvpc
    jobs:
    - job: Createvpc
      steps:
      - task: TerraformTaskV3@3
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/VPC'
          backendServiceAWS: 'aws-terraform'
          backendAWSBucketName: 'terraform-aws-1075'
          backendAWSKey: 'terraform.tfstate'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'aws'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/VPC'
          environmentServiceNameAWS: 'aws-terraform'

      - task: TerraformTaskV3@3
        inputs:
          provider: 'aws'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/VPC'
          environmentServiceNameAWS: 'aws-terraform'
          
  
    


  
                  
     
