apiVersion: apps/v1
kind: Deployment
metadata:
  name: gkeapp
  labels:
    app: gkeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gkeapp
  template:
    metadata:
      labels:
        app: gkeapp
    spec:
      containers:
      - name: gkeap
        image: abidh786/httpd-image:76
        ports:
        - containerPort: 80
        volumeMounts:
          - name: mypvc
            mountPath: /secrets
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc       
---
apiVersion: v1
kind: Service
metadata:
  name: gkeservice
  labels:
    app: gkeapp
spec:
  selector:
    app: gkeapp
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gkeingress
  labels:
    name: gkeingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gkeservice
            port: 
              number: 80
      
      
      



        
