apiVersion: apps/v1
kind: Deployment
metadata:
  name: gkeapp
  labels:
    app: gkeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gkeapp
  template:
    metadata:
      labels:
        app: gkeapp
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
      - name: gkeap
        image: abidh786/httpd-image:76
        env:
          - name: PORT
            value: "80"
          - name: DB_PORT
            value: "3306"
          - name: INSTANCE_HOST 
            value: "127.0.0.1"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysqldbpassword
                key:  user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysqldbpassword
                key:  password
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-instances=folkloric-union-370015:us-east1:mysql-2022=tcp:3306"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true             

        ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: gkeservice
  labels:
    app: gkeapp
spec:
  selector:
    app: gkeapp
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gkeingress
  labels:
    name: gkeingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gkeservice
            port: 
              number: 80
      
      
      



        
