apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip

spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gkeservice
            port: 
              number: 80

      - pathType: Prefix
        path: "/app2"
        backend:
          service:
            name: gkeservice2
            port: 
              number: 80        
