apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 50
  
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: my-pv-claim
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4


    
